import { Open_Sans } from 'next/font/google';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

import style from './layout.module.css';
const openSans = Open_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
})

import Logo from '../images/genspark-logo.svg';
import Image from 'next/image';

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={openSans.className}>
      <head>
        <title>Genspark Consulting</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
      </head>
      <body>
        <div className={style.wrapper}>
          <header className={style.header}>
            <Image src={Logo} width={253} height={32} style={{ display: 'block' }} alt="Genspark Consulting" />
          </header>
          <main className={style.main}>
            {children}
          </main>
          <footer className={style.footer}>&copy; {new Date().getFullYear()} Genspark Consulting</footer>
        </div>
      </body>
    </html>
  )
}
